### ISSUE TITLE
Nodes without GPUs may have nvidia-smi installed leading to incorrect GPU settings 

### ISSUE THREAD

**Issue by bjoo** [kokkos/hpcbind#1]
Some nodes may have nvidia-smi installed without having GPUs or GPU driver installed.
In this case nvidia-smi will be found (sets HPCBIND_VISIBLE_GPUS) and the
command used to find the number of GPUs outputs:

"NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."

and this registers as 2 lines and hence sets NUM_GPUS to 2 (because it is 2 lines long).
This may be harmless...

**Comment by dsunder** [comment]
Fixed
