### ISSUE TITLE
Deprecated --openmp-percent is actually broken

### ISSUE THREAD

**Issue by bartgol** [kokkos/hpcbind#3]
If I specify openmp-percent instead of openmp-ratio, I get the error message

`/home/lbertag/bin/hpcbind: line 240: 100: command not found`

It looks like the syntax for dividing 100 by openmp-percent value is wrong. But perhaps openmp-percent can be removed altogether?

**Comment by dsunder** [comment]
This is a bug that I’ll be fixing shortly (~30 mins).  I’ll email you when I push the fix.

--Dan

**Comment by dsunder** [comment]
Fixed
